baseurl: /
languageCode: en-us
title: Eric Bratu
theme: hugo-ivy
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2

params:
  description: "Third-year undergraduate student studying Computer Science at the University of Florida."
  footer: "<small>© Eric Bratu 2024 |  <a href=\"/EricBratuResume.pdf\" download>Resume</a> | [LinkedIn](https://www.linkedin.com/in/ericbratu/) | [GitHub](https://github.com/ericbratu) | [Instagram](https://www.instagram.com/eric.bratu)"


markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
