baseurl: "https://ericbratu.github.io/my-ivy-site/"
languageCode: en-us
title: Eric Bratu
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Experience"
      url: "/experience/"
      weight: 2
    - name: "Projects"
      url: "/projects/"
      weight: 3

params:
  description: "CS student at the University of Florida"
  footer: "<small>© Eric Bratu 2025 | <a href=\"/EricBratuResume.pdf\" download>Resume</a> | [LinkedIn](https://www.linkedin.com/in/ericbratu/) | [GitHub](https://github.com/ericbratu) | <a href=\"mailto:ericbratu15@gmail.com\">Email</a>"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
